<!DOCTYPE html>
<html lang="en">
<head>
    <link type="text/css" rel="stylesheet" href="/css/bootstrap.min.css" media="all">
    <link type="text/css" rel="stylesheet" href="/css/bootstrap-responsive.css" media="all">
    <link type="text/css" rel="stylesheet" href="/css/styles.css" media="all">
</head>
<body>
    <div class="container-fluid">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <ul class="nav">
                        <li><a href="/admin">Admin</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <form action="" method="post">
            <h3>Login</h3>

            <p>Username</p>
            <input type="text" name="username" />

            <p>Password</p>
            <input type="password" name="password" />

            <p><input type="submit" value="Submit" /></p>
            <?php
            if ($error) {
                echo '<p class="text-error">' . $error . '</p>';
            }
            ?>
        </form>
    </div>
</body>
</html>